// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "hero": { "eyebrow": string; "title": string; "note": string }; "principles": Array<{ "title": string; "body": string; "id": string }>; "invitation": { "folio": string; "label": string }; "footer": { "closing": string } } };
  export const home: { "hero": { "eyebrow": string; "title": string; "note": string }; "principles": Array<{ "title": string; "body": string; "id": string }>; "invitation": { "folio": string; "label": string }; "footer": { "closing": string } };
}
